In [1]:
import os
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA

In [2]:
os.listdir()

['djia_index.csv',
 'close_prices.csv',
 'task_1.ipynb',
 '.ipynb_checkpoints',
 'salary-train.csv',
 'salary-test-mini.csv',
 'task_2.ipynb',
 'ans_1']

In [3]:
files = os.listdir()[0:2]

In [41]:
df_1 = pd.read_csv(files[1], index_col='date', parse_dates=True)
df_2 = pd.read_csv(files[0])

In [5]:
df_1.head()

AXP          BA        CAT       CSCO         CVX  \
date                                                                  
2013-09-23  76.440002  117.510002  85.029999  24.270000  125.519997   
2013-09-24  76.070000  119.000000  85.110001  24.139999  124.489998   
2013-09-25  75.989998  118.510002  84.500000  24.430000  124.070000   
2013-09-26  76.320000  119.379997  84.199997  23.770000  123.489998   
2013-09-27  75.889999  118.739998  83.800003  23.330000  122.639999   

                   DD        DIS         GE          GS         HD  ...  \
date                                                                ...   
2013-09-23  59.409999  64.750000  24.280001  165.250000  75.910004  ...   
2013-09-24  59.319997  64.320000  24.320000  162.970001  76.040001  ...   
2013-09-25  59.319997  64.449997  24.230000  162.309998  75.519997  ...   
2013-09-26  59.509996  65.239998  24.250000  162.289993  76.070000  ...   
2013-09-27  59.009995  65.190002  24.049999  159.850006  75.959999  ...   

                  PFE         PG          T        TRV        UNH         UTX  \
date                                                                            
2013-09-23  28.799999  79.279999  34.220001  86.379997  71.820000  109.419998   
2013-09-24  28.709999  78.620003  34.090000  85.870003  72.320000  110.000000   
2013-09-25  28.490000  77.720001  34.049999  85.980003  71.980003  109.260002   
2013-09-26  28.520000  78.050003  34.230000  85.830002  72.160004  109.660004   
2013-09-27  28.879999  77.209999  33.980000  85.410004  71.989998  109.360001   

                     V         VZ        WMT        XOM  
date                                                     
2013-09-23  196.240005  47.980000  76.419998  87.750000  
2013-09-24  193.339996  47.270000  75.750000  87.360001  
2013-09-25  191.559998  46.950001  74.650002  87.139999  
2013-09-26  193.559998  47.669998  74.620003  87.070000  
2013-09-27  193.050003  47.000000  74.360001  86.900002  

[5 rows x 30 columns]

In [42]:
df_2.head()

date          ^DJI
0  2013-09-23  15401.379883
1  2013-09-24  15334.589844
2  2013-09-25  15273.259766
3  2013-09-26  15328.299805
4  2013-09-27  15258.240234

In [7]:
pca = PCA(n_components=10)
pca.fit(df_1)

PCA(n_components=10)

In [58]:
#ans_1
pca.explained_variance_ratio_[0:4]

array([0.73897118, 0.11007169, 0.04995088, 0.0287492 ])

In [87]:
with open('ans_2_1', 'w') as f:
    f.write('4')

In [49]:
#ans_2
comp = pd.DataFrame(pca.transform(df_1))
comp[0].values

array([-50.90240358, -52.84690919, -54.61443917, -52.60056628,
       -52.3701233 , -54.65341197, -52.81257496, -53.6511457 ,
       -56.69272698, -54.40265506, -58.33164549, -61.71626498,
       -61.31940025, -53.79252445, -50.89263448, -49.63740755,
       -52.3876147 , -47.47854294, -43.56033499, -42.55928046,
       -42.45027087, -42.27124797, -43.25272816, -40.05934481,
       -38.49726315, -39.06492263, -38.39304378, -38.40055833,
       -42.38616981, -39.83057417, -41.29548604, -40.43554958,
       -38.49607932, -42.96158052, -38.71252143, -38.83379331,
       -39.90606174, -37.58824522, -34.92356725, -32.96232694,
       -34.52461722, -36.40345948, -37.22194659, -32.95883861,
       -30.59159319, -29.63686919, -27.34513869, -26.90264007,
       -27.41985754, -28.24277351, -31.79501246, -31.39698179,
       -33.14502283, -30.41497345, -30.73495319, -32.3505575 ,
       -30.84313809, -32.84916115, -30.36248061, -29.89452878,
       -25.10690112, -19.92249325, -19.83315396, -19.22

In [45]:
df_2['^DJI'].values

array([15401.379883, 15334.589844, 15273.259766, 15328.299805,
       15258.240234, 15129.669922, 15191.700195, 15133.139648,
       14996.480469, 15072.580078, 14936.240234, 14776.530273,
       14802.980469, 15126.070312, 15237.110352, 15301.259766,
       15168.009766, 15373.830078, 15371.650391, 15399.650391,
       15392.200195, 15467.660156, 15413.330078, 15509.209961,
       15570.280273, 15568.929688, 15680.349609, 15618.759766,
       15545.75    , 15615.549805, 15639.120117, 15618.219727,
       15746.879883, 15593.980469, 15761.780273, 15783.099609,
       15750.669922, 15821.629883, 15876.219727, 15961.700195,
       15976.019531, 15967.030273, 15900.820312, 16009.990234,
       16064.769531, 16072.540039, 16072.799805, 16097.330078,
       16086.410156, 16008.769531, 15914.620117, 15889.769531,
       15821.509766, 16020.200195, 16025.530273, 15973.129883,
       15843.530273, 15739.429688, 15755.360352, 15884.570312,
       15875.259766, 16167.969727, 16179.080078, 16221.

In [46]:
np.corrcoef(comp[0].values, df_2['^DJI'].values)

array([[1.        , 0.90965222],
       [0.90965222, 1.        ]])

In [63]:
result = np.round(np.corrcoef(comp[0].values, df_2['^DJI'].values)[0][1], 2).astype('str')

In [64]:
result

'0.91'

In [88]:
with open('ans_2_2', 'w') as f:
    f.write(result)
    

In [86]:
#ans_3
res_3 = pca.components_[0].tolist()
res_3 = res_3.index(max(res_3))
with open('ans_2_3', 'w') as f:
    f.write(df_1.columns[res_3])